### ISSUE TITLE
Post Bytes in the discord?

### ISSUE THREAD

**Issue by mrphlip** [andreasots/eris#690]
Now that LRR is on Byte, perhaps we should consider auto-posting them in the `#lrrbot` channel on the discord?

Pros: more content, people without the app might not be aware they exist when new ones come out.
Cons: API isn't public yet, undocumented and not necessarily stable, need to do shenanigans with the app to get an auth token.

I don't know Rust so I can't really contribute the actual code, but the rough outline of the process is:
* Download https://api.byte.co/account/id/TV64KZLHS5FT3N4NKMU4ZBAHNQ/posts
* Pass header `Authorization: [token]` - I can get you a token
* De-json, loop through the clips
```
for clip in resp.data.posts:
  if clip.id not already posted:
    post(clip.shareURL)
```

**Comment by andreasots** [comment]
Byte is dead.
